name: lpytraining
channels:
  - fredboudon
  - conda-forge
dependencies:
  - openalea.plantgl=3.10.*
  - openalea.lpy=3.8.*
  - openalea.plantscan3d
  #- alinea.caribu
  - jupyterlab>=3.0.16
  - jupyterlab_widgets
  - ipython=7
  - matplotlib
  - numpy=1.20.*
  - pandas
  - scipy
  - pip
  - pip:
    - pgljupyter>=1.2.*
